# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1

tr:
  languageCode: tr-tr
  contentDir: content-tr
  title: Doç.Dr. Alper YILMAZ
  params:
    description: Kişisel web sayfam..
  menu:
    main:
      - name: Ana sayfa
        url: '#about'
        weight: 1
      - name: Yazılar
        url: '#posts'
        weight: 2
      - name: Projeler
        url: '#publications'
        weight: 3
      - name: Yayınlar
        url: '#publications'
        weight: 4
      
